version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: guardflow_postgres
    environment:
      POSTGRES_USER: guardflow
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guardflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guardflow"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: guardflow_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis Commander for GUI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: guardflow_redis_gui
    environment:
      REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - tools

  # Optional: pgAdmin for PostgreSQL GUI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: guardflow_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@guardflow.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    profiles:
      - tools

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: guardflow_network