"""Add password field to users table

Revision ID: 033532944b2e
Revises: fc72097a1c6f
Create Date: 2025-08-03 00:01:34.910567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033532944b2e'
down_revision = 'fc72097a1c6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###