"""add_progress_tracking_fields_to_user_task

Revision ID: 60c7874b2dbb
Revises: 8530430d6b58
Create Date: 2025-08-03 03:40:54.865882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c7874b2dbb'
down_revision = '8530430d6b58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('progress_notes', sa.Text(), nullable=True))
    op.add_column('user_tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_tasks', sa.Column('daily_quota_limit', sa.Integer(), nullable=True))
    op.add_column('user_tasks', sa.Column('max_tokens_per_request', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'max_tokens_per_request')
    op.drop_column('user_tasks', 'daily_quota_limit')
    op.drop_column('user_tasks', 'completed_at')
    op.drop_column('user_tasks', 'progress_notes')
    # ### end Alembic commands ###