"""rename_daily_quota_limit_to_token_limit

Revision ID: 6ab32ea4171c
Revises: d89a87b4fba3
Create Date: 2025-08-03 04:29:03.331433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab32ea4171c'
down_revision = 'd89a87b4fba3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('token_limit', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'daily_quota_limit')
    op.add_column('user_tasks', sa.Column('token_limit', sa.Integer(), nullable=True))
    op.drop_column('user_tasks', 'daily_quota_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('daily_quota_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_tasks', 'token_limit')
    op.add_column('tasks', sa.Column('daily_quota_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'token_limit')
    # ### end Alembic commands ###