"""Update Task model with frontend fields

Revision ID: 8530430d6b58
Revises: 033532944b2e
Create Date: 2025-08-03 00:19:41.961237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8530430d6b58'
down_revision = '033532944b2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('tasks', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('difficulty_level', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('estimated_hours', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('max_tokens_per_request', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('daily_quota_limit', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'daily_quota_limit')
    op.drop_column('tasks', 'max_tokens_per_request')
    op.drop_column('tasks', 'estimated_hours')
    op.drop_column('tasks', 'difficulty_level')
    op.drop_column('tasks', 'category')
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###