"""add_alert_system_and_per_request_limits

Revision ID: 99e992a6f41e
Revises: c73c2b382a02
Create Date: 2025-08-03 12:53:42.112619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e992a6f41e'
down_revision = 'c73c2b382a02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('max_tokens_per_request', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'max_tokens_per_request')
    # ### end Alembic commands ###