"""add_is_dummy_task_field_to_tasks

Revision ID: d02f968f7adc
Revises: 8a250d3e55eb
Create Date: 2025-08-15 12:46:10.166084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd02f968f7adc'
down_revision = '8a250d3e55eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_api_keys_is_active', table_name='api_keys')
    op.drop_index('idx_api_keys_key_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_tenant_id', table_name='api_keys')
    op.drop_index('idx_api_keys_user_id', table_name='api_keys')
    op.add_column('tasks', sa.Column('is_dummy_task', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tasks_is_dummy_task'), 'tasks', ['is_dummy_task'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_is_dummy_task'), table_name='tasks')
    op.drop_column('tasks', 'is_dummy_task')
    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_index('idx_api_keys_tenant_id', 'api_keys', ['tenant_id'], unique=False)
    op.create_index('idx_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_is_active', 'api_keys', ['is_active'], unique=False)
    op.alter_column('api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###