"""remove_max_tokens_per_request_and_make_estimated_hours_optional

Revision ID: d89a87b4fba3
Revises: 60c7874b2dbb
Create Date: 2025-08-03 04:16:12.320706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89a87b4fba3'
down_revision = '60c7874b2dbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'max_tokens_per_request')
    op.drop_column('user_tasks', 'max_tokens_per_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('max_tokens_per_request', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('max_tokens_per_request', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###