"""ensure_admin_roles_and_permissions

Revision ID: efe34b1df734
Revises: d02f968f7adc
Create Date: 2025-08-16 00:07:57.807997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe34b1df734'
down_revision = 'd02f968f7adc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###