version: '3.8'

services:
  # React Frontend
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: guardflow_frontend_prod
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - guardflow-frontend-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  guardflow-frontend-network:
    driver: bridge
    name: guardflow_frontend_production